In [121]:
import numpy as np
import pandas as pd

In [122]:
df = pd.read_csv('healthcare_test.csv')

In [123]:
df.head()

,documents/name,documents/fields/idNumber/stringValue,documents/fields/surname/stringValue,documents/fields/healthData/mapValue/fields/bloodPressureSystolic/integerValue,documents/fields/healthData/mapValue/fields/weight/doubleValue,documents/fields/healthData/mapValue/fields/temperature/doubleValue,documents/fields/healthData/mapValue/fields/height/doubleValue,documents/fields/healthData/mapValue/fields/tookAntihypertensive/booleanValue,documents/fields/healthData/mapValue/fields/bmi/doubleValue,documents/fields/healthData/mapValue/fields/bloodSugar/doubleValue,...,documents/fields/gender/stringValue,documents/fields/updatedAt/timestampValue,documents/createTime,documents/updateTime,documents/fields/healthData/mapValue/fields/bloodOxygen/integerValue,documents/fields/healthData/mapValue/fields/height/integerValue,documents/fields/healthData/mapValue/fields/bloodSugar/integerValue,documents/fields/healthData/mapValue/fields/weight/integerValue,documents/fields/healthData/mapValue/fields/temperature/integerValue,documents/fields/healthData/mapValue/fields/bmi/integerValue
0,projects/healthcare-test01/databases/(default)...,1269900350207,พรหมณี,105,76.0,36.8,139.0,True,39.3,73.0,...,Other,2025-02-04T10:50:11.227Z,2025-02-04T10:41:49.482614Z,2025-02-04T10:50:09.629176Z,NaN,NaN,NaN,NaN,NaN,NaN
1,projects/healthcare-test01/databases/(default)...,3100700640618,กังวล,75,74.5,35.5,NaN,NaN,29.1,NaN,...,Female,2025-01-24T08:48:13.164Z,2025-01-24T08:48:13.542605Z,2025-01-24T08:48:13.542605Z,100.0,160.0,100.0,NaN,NaN,NaN
2,projects/healthcare-test01/databases/(default)...,3102201532596,ศรีระยับ,150,NaN,35.9,NaN,NaN,29.6,NaN,...,Female,2025-01-24T09:32:22.245Z,2025-01-24T09:32:22.693891Z,2025-01-24T09:32:22.693891Z,97.0,155.0,145.0,71.0,NaN,NaN
3,projects/healthcare-test01/databases/(default)...,3150300024529,ไม้เนียม,128,NaN,36.5,NaN,NaN,21.9,NaN,...,Female,2025-01-24T09:30:03.037Z,2025-01-24T09:30:03.029029Z,2025-01-24T09:30:03.029029Z,99.0,151.0,108.0,50.0,NaN,NaN
4,projects/healthcare-test01/databases/(default)...,3250500511902,จะละสุ,126,NaN,36.3,NaN,NaN,20.5,NaN,...,Female,2025-01-24T09:28:59.259Z,2025-01-24T09:28:59.257203Z,2025-01-24T09:28:59.257203Z,100.0,156.0,106.0,50.0,NaN,NaN

In [124]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 25 columns):
 #   Column                                                                           Non-Null Count  Dtype
---  ------                                                                           --------------  -----
 0   documents/name                                                                   27 non-null     object
 1   documents/fields/idNumber/stringValue                                            27 non-null     int64
 2   documents/fields/surname/stringValue                                             27 non-null     object
 3   documents/fields/healthData/mapValue/fields/bloodPressureSystolic/integerValue   27 non-null     int64
 4   documents/fields/healthData/mapValue/fields/weight/doubleValue                   3 non-null      float64
 5   documents/fields/healthData/mapValue/fields/temperature/doubleValue              25 non-null     float64
 6   documents/fields/healthData/mapValue/fields/height/doubleValue                   1 non-null      float64
 7   documents/fields/healthData/mapValue/fields/tookAntihypertensive/booleanValue    1 non-null      object
 8   documents/fields/healthData/mapValue/fields/bmi/doubleValue                      26 non-null     float64
 9   documents/fields/healthData/mapValue/fields/bloodSugar/doubleValue               1 non-null      float64
 10  documents/fields/healthData/mapValue/fields/bloodOxygen/doubleValue              1 non-null      float64
 11  documents/fields/healthData/mapValue/fields/bloodPressureDiastolic/integerValue  27 non-null     int64
 12  documents/fields/createdAt/timestampValue                                        27 non-null     object
 13  documents/fields/name/stringValue                                                27 non-null     object
 14  documents/fields/age/integerValue                                                27 non-null     int64
 15  documents/fields/gender/stringValue                                              27 non-null     object
 16  documents/fields/updatedAt/timestampValue                                        27 non-null     object
 17  documents/createTime                                                             27 non-null     object
 18  documents/updateTime                                                             27 non-null     object
 19  documents/fields/healthData/mapValue/fields/bloodOxygen/integerValue             26 non-null     float64
 20  documents/fields/healthData/mapValue/fields/height/integerValue                  26 non-null     float64
 21  documents/fields/healthData/mapValue/fields/bloodSugar/integerValue              26 non-null     float64
 22  documents/fields/healthData/mapValue/fields/weight/integerValue                  24 non-null     float64
 23  documents/fields/healthData/mapValue/fields/temperature/integerValue             2 non-null      float64
 24  documents/fields/healthData/mapValue/fields/bmi/integerValue                     1 non-null      float64
dtypes: float64(12), int64(4), object(9)
memory usage: 5.4+ KB

In [125]:
df = df.drop(columns=['documents/name','documents/fields/updatedAt/timestampValue','documents/createTime','documents/updateTime','documents/fields/createdAt/timestampValue'])

In [126]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 20 columns):
 #   Column                                                                           Non-Null Count  Dtype
---  ------                                                                           --------------  -----
 0   documents/fields/idNumber/stringValue                                            27 non-null     int64
 1   documents/fields/surname/stringValue                                             27 non-null     object
 2   documents/fields/healthData/mapValue/fields/bloodPressureSystolic/integerValue   27 non-null     int64
 3   documents/fields/healthData/mapValue/fields/weight/doubleValue                   3 non-null      float64
 4   documents/fields/healthData/mapValue/fields/temperature/doubleValue              25 non-null     float64
 5   documents/fields/healthData/mapValue/fields/height/doubleValue                   1 non-null      float64
 6   documents/fields/healthData/mapValue/fields/tookAntihypertensive/booleanValue    1 non-null      object
 7   documents/fields/healthData/mapValue/fields/bmi/doubleValue                      26 non-null     float64
 8   documents/fields/healthData/mapValue/fields/bloodSugar/doubleValue               1 non-null      float64
 9   documents/fields/healthData/mapValue/fields/bloodOxygen/doubleValue              1 non-null      float64
 10  documents/fields/healthData/mapValue/fields/bloodPressureDiastolic/integerValue  27 non-null     int64
 11  documents/fields/name/stringValue                                                27 non-null     object
 12  documents/fields/age/integerValue                                                27 non-null     int64
 13  documents/fields/gender/stringValue                                              27 non-null     object
 14  documents/fields/healthData/mapValue/fields/bloodOxygen/integerValue             26 non-null     float64
 15  documents/fields/healthData/mapValue/fields/height/integerValue                  26 non-null     float64
 16  documents/fields/healthData/mapValue/fields/bloodSugar/integerValue              26 non-null     float64
 17  documents/fields/healthData/mapValue/fields/weight/integerValue                  24 non-null     float64
 18  documents/fields/healthData/mapValue/fields/temperature/integerValue             2 non-null      float64
 19  documents/fields/healthData/mapValue/fields/bmi/integerValue                     1 non-null      float64
dtypes: float64(12), int64(4), object(4)
memory usage: 4.3+ KB

In [128]:
df.columns= ['ID','Surname','Systolic','Weight','Temperature','Height','tookAntihypertensive','BMI','Glucose','Oxygen','Diastolic','Name','Age','Gender','']

ValueError: Length mismatch: Expected axis has 20 elements, new values have 15 elements